org:
  auth_token: 3g_XB6e8BKkEp3M_HiNHlg
  repositories:
    #ci_travis_radar: Vindicarian/dashboard
    ci_travis_radar: pivotal/cedar
    #ci_travis_radar: pivotal/jasmine
    #NO JASMINE??
  type: org

# pro:
#   auth_token: my_pro_auth_token
#   repositories:
#     ci_travis_zendesk: zendesk/zendesk
#   type: pro
