org:
  auth_token: 3g_XB6e8BKkEp3M_HiNHlg
  repositories:
    ci_travis_radar: Vindicarian/dashboard
  type: org

# pro:
#   auth_token: my_pro_auth_token
#   repositories:
#     ci_travis_zendesk: zendesk/zendesk
#   type: pro
